version: '3'
services:
  postgres:
    # image: postgres:latest
    build: 
      context: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  payload:
    image: node:18-alpine
    working_dir: /home/node/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - "3000:3000"
    command: >
      sh -c "corepack enable &&
             corepack prepare pnpm@latest --activate &&
             pnpm install &&
             pnpm dev"

volumes:
  pgdata:
  node_modules:
  data: